### PR TITLE
Fix-unhandled-exception 

### LINKED ISSUE #26: Unhandled exception
**Describe the bug**
Unhandled exception on index.js line 143

**To Reproduce**
App sporadically crashes - no distinct steps to reproduce.

**Screenshots**
IMG_8181

**Additional context**
Running latest library version on RN 0.73.6 on iOS 18.

### PR DESCRIPTION
**Pull request by herberthk**
## Fix  [issue](https://github.com/herberthk/react-native-viewport/issues/26)

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -74,10 +72,14 @@ class InViewport extends Component<InViewportProps, InViewportState> {
...
+   * Debounce handleVisibilityChange for performance
    */
-  handleVisibilityChange(isVisible: boolean) {
-    this.props.onChange(isVisible);
-  }
+  handleVisibilityChange = debounce((isVisible: boolean) => {
+    if (this.props.onChange) {
+      this.props.onChange(isVisible);
+    }
+  }, 200);
```
Comment (herberthk) [inline src/index.tsx:82]: LGTM
